cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$',
        views.order_create,
        name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.EmailField()
	address = models.CharField(max_length=250)
	postal_code = models.CharField(max_length=20)
	city = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items')
	product = models.ForeignKey(Product, related_name='order_items')
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])
	

class Product(models.Model):
	category = models.ForeignKey(Category, related_name='products')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	stock = models.PositiveIntegerField()
	available = models.BooleanField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

# Create your views here.
def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save()
			for item in cart:
				OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
			cart.clear()
			return render(request, 'orders/order/created.html', {'order': order})
	else:
		form = OrderCreateForm()
	return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

# Create your views here.
def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category)
	return render(
					request, 
					'shop/product/list.html', 
					{'category': category,
					 'categories': categories,
					 'products': products}
				)

def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	return render(
				   request,
				  'shop/product/detail.html',
				  {'product': product, 'cart_product_form': cart_product_form}
				  )

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart panel-group table">
    <div class="panel panel-default">
    <thead class="panel-heading">
      <tr>
        <th class="panel-heading">Image</th>
        <th class="panel-heading">Product</th>
        <th class="panel-heading">Quantity</th>
        <th class="panel-heading">Remove</th>
        <th class="panel-heading">Unit price</th>                
        <th class="panel-heading">Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr class="table-hover">
            <td class="panel-heading">
              <a href="{{ product.get_absolute_url }}">
                <img style="width: 200px; height: 200px;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">                    
              </a>
            </td>
            <td class="panel-heading">{{ product.name }}</td>
            <td class="panel-heading">{{ item.quantity }}</td>
            <td class="panel-heading"><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
            <td class="num panel-heading">${{ item.price }}</td>
            <td class="num panel-heading">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total panel-footer">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
    </div>
  </table>
  <p class="text-right">
    <div  class="btn btn-default"><a href="{% url "shop:product_list" %}">Continue shopping</a></div>
    <div  class="btn btn-info"><a href="{% url "orders:order_create" %}">Checkout</a></div>
  </p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
<h1>Checkout</h1>
<div class="row">
  
  
    
  <div class="order-info panel panel-default col-lg-6" style="padding:30px 50px">
    <h3>Your order</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }} 
          <span>€{{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
    <p><strong>Total:</strong> €{{ cart.get_total_price }}</p>
  </div>

  <form action="." method="post" class="order-form form-group col-lg-6" style="padding-left: 50px">
    {{ form.as_p }}
    <p><input type="submit" value="Place order" class="btn btn-info"></p>
    {% csrf_token %}
  </form>
    
</div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Toats Ma Goats{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Toats Ma Goats</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="#">Shop</a></li>
      <li class="dropdown cart">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="badge">{% with total_items=cart|length %}{{ total_items }}{% endwith %}</span><i class="fa fa-shopping-cart" style="font-size:20px"></i>
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li>
          {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            <a href="{% url "cart:cart_detail" %}">
              Your cart: 
              {{ total_items }} item{{ total_items|pluralize }},
              €{{ cart.get_total_price }}
            </a>
          {% else %}
            Your cart is empty.
          {% endif %}
        {% endwith %}
      </li>
        </ul>
      </li>
    </ul>
  </div>
  </nav>
  {% block carousel %}
  {% endblock %}
  <div class="container" id="content">
    {% block content %}
    {% endblock %}
  </div>
  
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div class="product-detail row" style="display: flex; flex-wrap: wrap;">
    <img class="col-lg-5" style=" height: 500px;" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <div class="col-lg-7">
    <h1><strong>{{ product.name }}</strong></h1>
    <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
    <p>{{ product.description}}</p>
    <h3 class="price"><strong>€{{ product.price }}</strong></h3>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
  </div>
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block carousel %}
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="https://thumbs-prod.si-cdn.com/Y8YmcLIr3hO4HvYof2jBYmVHuIM=/800x600/filters:no_upscale()/https://public-media.smithsonianmag.com/filer/b9/d2/b9d271f3-7f66-4132-b5af-7d33844505b7/goat.jpg" alt="Chania">
     
    </div>

    <div class="item">
      <img src="https://www.veterantv.com/wp-content/uploads/2017/08/f5d784aa1eabbde15ba5e2d90c3ba828.jpg" alt="Chicago">
    </div>

    <div class="item">
      <img src="https://fthmb.tqn.com/Js2t1C70PCO9olMMP0hZfMkBBZY=/960x0/filters:no_upscale():max_bytes(150000):strip_icc()/boer-goats-resized-56a885723df78cf7729e87d2.jpg" alt="New York">
      
    </div>
    <div class="centered">
        <h1>Toats Ma Goats</h1>
        <p>The easiest platform for buying goats!</p>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}
{% block content %}
<div class="row">
  <div id="sidebar" class="col-lg-3 well">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list col-lg-9 panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>{% if category %}{{ category.name }}{% else %}Goats{% endif %}</h1>
      </div>
    <div class="row panel-body">
    {% for product in products %}
    <a href="{{ product.get_absolute_url }}">
      <div class="item col-lg-5" style="padding-top: 15px; width: 330px;">
        
          <img style="width: 300px; height: 280px" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        
        <div>
          <h3>{{ product.name }}</h3><br>
          <p>€{{ product.price }}</p><br>
        </div>
      </div>
    </a>
    {% endfor %}
    </div>
    </div>
  </div>
</div>
{% endblock %}